# Generated by Django 6.0.5 on 2026-05-28 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя артиста')),
                ('era', models.CharField(help_text='Например: 70s Funk, French House', max_length=50, verbose_name='Эпоха / Жанр')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название трека')),
                ('release_year', models.IntegerField(verbose_name='Год выпуска')),
                ('listen_link', models.URLField(blank=True, verbose_name='Ссылка на прослушивание')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='core.artist', verbose_name='Артист')),
            ],
        ),
        migrations.CreateModel(
            name='SampleRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('vocal', 'Вокал'), ('drum', 'Ударные (Drum Loop)'), ('bass', 'Басовая линия'), ('melody', 'Мелодия (Synth/Guitar)'), ('full', 'Полный кусок (Full Loop)')], max_length=20, verbose_name='Тип семпла')),
                ('timestamp', models.CharField(blank=True, max_length=10, verbose_name='Таймкод')),
                ('source_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampled_in', to='core.track', verbose_name='Оригинальный трек (Источник)')),
                ('target_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contains_samples', to='core.track', verbose_name='Новый трек (Куда вставили)')),
            ],
        ),
    ]
